name: Docker  latest

on:
  push:
    branches:
      - "feat/docker-img"

jobs:
  docker:
    name: Building docker image for ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Install docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Docker build
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 \
          -f docker/Dockerfile . \
          -t cocogitto/cocogitto:latest
